name: Create package on release

on: create

jobs:
  release:
    name: Create and release deb/rpm files
    runs-on: ubuntu-18.04
    env:
      CENTOS_VERSION: 7
      OPENSUSE_VERSION: 15.1
      GRIDDB_SERVER_NAME: "griddb"
      ADMIN_PASSWORD: "admin"
      DOCKER_CONTAINER_NAME_CENTOS: "dockerCentOS"
      DOCKER_CONTAINER_NAME_OPENSUSE: "dockerOpenSuse"
    steps:
      - uses: actions/checkout@v1

      - name: Build package for Ubuntu
        run: ./.github/workflows/build_package_ubuntu_docker.sh
          

      - name: Upload deb file
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ../griddb_*_amd64.deb
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: Build package for CentOS
        run: ./.github/workflows/build_package_centos_docker.sh

      - name: Upload rpm file
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: griddb-*.rpm
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: Build package for OpenSuse
        run: ./.github/workflows/build_package_opensuse_docker.sh

      - name: Upload rpm file
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: griddb-*.rpm
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
