name: Create package on release (test)

on: create

jobs:
  release:
    name: Create and release deb/rpm files (test)
    runs-on: ubuntu-18.04
    env:
      CENTOS_VERSION: 7
      OPENSUSE_VERSION: 15.1
      DOCKER_CONTAINER_NAME_CENTOS: "dockerCentOS"
      DOCKER_CONTAINER_NAME_OPENSUSE: "dockerOpenSuse"
    steps:
      - uses: actions/checkout@v1

      - name: Build package for OpenSuse
        run: ./.github/workflows/build_package_opensuse_docker.sh

      - name: Upload rpm file
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: griddb-*.rpm
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
