name: Create package on release

on: create

env:
  GRIDDB_SERVER_NAME: "griddb"
  GRIDDB_NOTIFICATION_ADDRESS: "239.0.0.1"
  GRIDDB_NOTIFICATION_PORT: "31999"
  GRIDDB_USERNAME: "admin"
  GRIDDB_PASSWORD: "admin"
  GRIDDB_PACKAGE_NAME: "griddb"

jobs:
  release_package:
    name: Create and release ${{ matrix.file_type }} file for ${{ matrix.os }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          - os: Ubuntu
            container: duongntt/griddb-ubuntu-18.04
            file_type: deb
            package_path: ../griddb_*_amd64.deb
          - os: Centos
            container: duongntt/griddb-centos7
            file_type: rpm
            package_path: installer/RPMS/x86_64/griddb-*-linux.x86_64.rpm
          - os: Opensuse
            container: duongntt/griddb-opensuse-15.1
            file_type: rpm
            package_path: installer/RPMS/x86_64/griddb-*-opensuse.x86_64.rpm

    container:
      image:  ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v1
      - name: Build Griddb server
        run: . .github/workflows/script/function.sh && build_griddb ${{ matrix.os }}
      - name: Create ${{ matrix.file_type }} for ${{ matrix.os }}
        run: . .github/workflows/script/function.sh && build_package ${{ matrix.os }}
      - name: Check package information
        run: . .github/workflows/script/function.sh \
             && check_package ${{ matrix.package_path }} ${{ matrix.os }}
      - name: Install package
        run: . .github/workflows/script/function.sh && install_griddb ${{ matrix.package_path }} ${{ matrix.os }}
      - name: Config GridDB server
        run: . .github/workflows/script/function.sh \
             && config_griddb ${GRIDDB_USERNAME} ${GRIDDB_PASSWORD} ${GRIDDB_SERVER_NAME}
      - name: Start server
        run: . .github/workflows/script/function.sh \
             && start_griddb ${GRIDDB_USERNAME} ${GRIDDB_PASSWORD} ${GRIDDB_SERVER_NAME}
      - name: Run sample
        run: . .github/workflows/script/function.sh \
             && run_sample ${GRIDDB_NOTIFICATION_ADDRESS} ${GRIDDB_NOTIFICATION_PORT} ${GRIDDB_SERVER_NAME} ${GRIDDB_USERNAME} ${GRIDDB_PASSWORD}
      - name: Stop server
        run: . .github/workflows/script/function.sh \
             && stop_griddb ${GRIDDB_USERNAME} ${GRIDDB_PASSWORD}
      - name: Uninstall package
        run: . .github/workflows/script/function.sh \
             && uninstall_package ${GRIDDB_PACKAGE_NAME} ${{ matrix.os }}
      - name: Upload ${{ matrix.file_type }} file
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.package_path }}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

