name: Create package on release

on: create

jobs:
  release:
    name: Create and release deb files
    runs-on: ubuntu-18.04
    env:
      GRIDDB_SERVER_NAME: "griddb"
      GRIDDB_NOTIFICATION_ADDRESS: "239.0.0.1"
      GRIDDB_NOTIFICATION_PORT: "31999"
      GRIDDB_USERNAME: "admin"
      GRIDDB_PASSWORD: "admin"
      CENTOS_VERSION: 7
      DOCKER_CONTAINER_NAME_CENTOS: "dockerCentOS"
    steps:
      - uses: actions/checkout@v1

      - name: Build package for Ubuntu
        run: ./.github/workflows/build_package_ubuntu.sh

      - name: Build package for CentOS
        run: ./.github/workflows/build_package_centos_docker.sh

      - name: Upload deb/rpm files
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ../griddb_*_amd64.deb ../griddb-*.rpm
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

