name: Create package on release

on: create

jobs:
  release:
    name: Create and release deb file
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Build package for Ubuntu
        run: |
          sudo apt-get install gcc-4.8
          sudo apt-get install g++-4.8
          sudo apt-get install tcl debhelper libz-dev libsqlite3-dev
          export CC=gcc-4.8
          export CC_FOR_BUILD=gcc-4.8
          export CXX=g++-4.8
          export CXX_FOR_BUILD=g++-4.8
          dpkg-buildpackage -b

      - name: Get Release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload deb file
        id: upload-release-asset 
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ../griddb_*_amd64.deb
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
