name: Create package on release

on: create

jobs:
  release:
    name: Create and release rpm file for CentOS7
    runs-on: ubuntu-18.04
    container: 
      image: duongntt/griddb-centos7
    env:
      GRIDDB_SERVER_NAME: "griddb"
      GRIDDB_NOTIFICATION_ADDRESS: "239.0.0.1"
      GRIDDB_NOTIFICATION_PORT: "31999"
      GRIDDB_USERNAME: "admin"
      GRIDDB_PASSWORD: "admin"
      GRIDDB_PACKAGE_NAME: "griddb"
    steps:
      - uses: actions/checkout@v1

      - name: Build Griddb server
        run: ./.github/workflows/script/centos/centos_build_griddb.sh

      - name: Create rpm for CentOS
        run: ./.github/workflows/script/centos/centos_build_griddb.sh



