name: Create package on release

on: create

env:
  GRIDDB_SERVER_NAME: "griddb"
  GRIDDB_NOTIFICATION_ADDRESS: "239.0.0.1"
  GRIDDB_NOTIFICATION_PORT: "31999"
  GRIDDB_USERNAME: "admin"
  GRIDDB_PASSWORD: "admin"
  GRIDDB_PACKAGE_NAME: "griddb"

jobs:
  release_rpm_centos_7:
    name: Create and release rpm file for CentOS7
    runs-on: ubuntu-18.04
    container: 
      image: duongntt/griddb-centos7
    steps:
      - uses: actions/checkout@v1
      - name: Build Griddb server
        run: . ./.github/workflows/script/function.sh && build_griddb
      - name: Create rpm for CentOS
        run: . ./.github/workflows/script/function.sh && build_rpm
      - name: Check package information
        run: rpm -qip installer/RPMS/x86_64/griddb-*-linux.x86_64.rpm
      - name: Install package
        run: . ./.github/workflows/script/function.sh && install_griddb
      - name: Config GridDB server
        run: |
          su -l gsadm -c "gs_passwd ${GRIDDB_USERNAME} -p ${GRIDDB_PASSWORD}"
          su -l gsadm -c "sed -i 's/\"clusterName\":\"\"/\"clusterName\":\"${GRIDDB_SERVER_NAME}\"/g' /var/lib/gridstore/conf/gs_cluster.json"
      - name: Start server
        run: |
          su -l gsadm -c "gs_startnode -w -u ${GRIDDB_USERNAME}/${GRIDDB_PASSWORD}"
          su -l gsadm -c "gs_joincluster -c ${GRIDDB_SERVER_NAME} -u ${GRIDDB_USERNAME}/${GRIDDB_PASSWORD} -w"
      - name: Run sample
        run: . ./.github/workflows/script/function.sh && run_sample ${GRIDDB_NOTIFICATION_ADDRESS} ${GRIDDB_NOTIFICATION_PORT} ${GRIDDB_SERVER_NAME} ${GRIDDB_USERNAME} ${GRIDDB_PASSWORD}
      - name: Stop server
        run: |
          su -l gsadm -c "gs_stopcluster -u ${GRIDDB_USERNAME}/${GRIDDB_PASSWORD} -w"
          su -l gsadm -c "gs_stopnode -u ${GRIDDB_USERNAME}/${GRIDDB_PASSWORD} -w"
      - name: Uninstall package
        run: rpm -e ${GRIDDB_PACKAGE_NAME}
      - name: Upload rpm file
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: installer/RPMS/x86_64/griddb-*-linux.x86_64.rpm
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

  release_rpm_opensuse15_1:
    name: Create and release rpm file for OpenSuse15.1
    runs-on: ubuntu-18.04
    container: 
      image: duongntt/griddb-opensuse-15.1
    steps:
      - uses: actions/checkout@v1

      - name: Build Griddb server
        run: . ./.github/workflows/script/function.sh && build_griddb
      - name: Create rpm for OpenSuse
        run: . ./.github/workflows/script/function.sh && build_rpm
      - name: Check package information
        run: rpm -qip installer/RPMS/x86_64/griddb-*-linux.x86_64.rpm
      - name: Install package
        run: . ./.github/workflows/script/function.sh && install_griddb
      - name: Config GridDB server
        run: |
          su -l gsadm -c "gs_passwd ${GRIDDB_USERNAME} -p ${GRIDDB_PASSWORD}"
          su -l gsadm -c "sed -i 's/\"clusterName\":\"\"/\"clusterName\":\"${GRIDDB_SERVER_NAME}\"/g' /var/lib/gridstore/conf/gs_cluster.json"
      - name: Start server
        run: |
          su -l gsadm -c "gs_startnode -w -u ${GRIDDB_USERNAME}/${GRIDDB_PASSWORD}"
          su -l gsadm -c "gs_joincluster -c ${GRIDDB_SERVER_NAME} -u ${GRIDDB_USERNAME}/${GRIDDB_PASSWORD} -w"
      - name: Run sample
        run: . ./.github/workflows/script/function.sh && run_sample ${GRIDDB_NOTIFICATION_ADDRESS} ${GRIDDB_NOTIFICATION_PORT} ${GRIDDB_SERVER_NAME} ${GRIDDB_USERNAME} ${GRIDDB_PASSWORD}
      - name: Stop server
        run: |
          su -l gsadm -c "gs_stopcluster -u ${GRIDDB_USERNAME}/${GRIDDB_PASSWORD} -w"
          su -l gsadm -c "gs_stopnode -u ${GRIDDB_USERNAME}/${GRIDDB_PASSWORD} -w"
      - name: Uninstall package
        run: rpm -e ${GRIDDB_PACKAGE_NAME}
      - name: Change package name
        run: . ./.github/workflows/script/function.sh && opensuse_change_package_name
      - name: Upload rpm file
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: installer/RPMS/x86_64/griddb-*-opensuse.x86_64.rpm
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

  release_deb_ubuntu_18_04:
    name: Create and release deb file for Ubuntu 18.04
    runs-on: ubuntu-18.04
    container: 
      image: duongntt/griddb-ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Create deb file for Ubuntu
        run: dpkg-buildpackage -b
      - name: Check package information
        run: dpkg-deb -I ../griddb_*_amd64.deb
      - name: Install package
        run: dpkg -i ../griddb_*_amd64.deb
      - name: Config GridDB server
        run: |
          su -l gsadm -c "gs_passwd ${GRIDDB_USERNAME} -p ${GRIDDB_PASSWORD}"
          su -l gsadm -c "sed -i 's/\"clusterName\":\"\"/\"clusterName\":\"${GRIDDB_SERVER_NAME}\"/g' /var/lib/gridstore/conf/gs_cluster.json"
      - name: Start server
        run: |
          su -l gsadm -c "gs_startnode -w -u ${GRIDDB_USERNAME}/${GRIDDB_PASSWORD}"
          su -l gsadm -c "gs_joincluster -c ${GRIDDB_SERVER_NAME} -u ${GRIDDB_USERNAME}/${GRIDDB_PASSWORD} -w"
      - name: Run sample
        run: . .github/workflows/script/function.sh && run_sample ${GRIDDB_NOTIFICATION_ADDRESS} ${GRIDDB_NOTIFICATION_PORT} ${GRIDDB_SERVER_NAME} ${GRIDDB_USERNAME} ${GRIDDB_PASSWORD}
      - name: Stop server
        run: |
          su -l gsadm -c "gs_stopcluster -u ${GRIDDB_USERNAME}/${GRIDDB_PASSWORD} -w"
          su -l gsadm -c "gs_stopnode -u ${GRIDDB_USERNAME}/${GRIDDB_PASSWORD} -w"
      - name: Uninstall package
        run: rpm -e ${GRIDDB_PACKAGE_NAME}
      - name: Upload deb file
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ../griddb-*.deb
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

